# Generated by Django 2.0 on 2017-12-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('barcode', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('energy_100g', models.FloatField()),
                ('fat_100g', models.FloatField()),
                ('saturated_fat_100g', models.FloatField()),
                ('carbohydrates_100g', models.FloatField()),
                ('sugar_100g', models.FloatField()),
                ('protein_100g', models.FloatField()),
                ('salt_100g', models.FloatField()),
            ],
        ),
    ]
