# Generated by Django 2.0.2 on 2018-02-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python4TW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg', max_length=255),
            preserve_default=False,
        ),
    ]
